// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thaghdaioherrbiyjpnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoYWdoZGFpb2hlcnJiaXlqcG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjY3NTEsImV4cCI6MjA3MjUwMjc1MX0.a4MTpGkd4GaCvWy14wtyjkkivWOsfaBpiL9jVfZilJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});